2022-09-05 15:35:33,279 ERROR: Exception on /translate [POST] [in /usr/lib/python3.10/site-packages/flask/app.py:1455
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/src/app/routes.py", line 203, in translate_text
    return jsonify({'text': translate(request.form['text'],
NameError: name 'jsonify' is not defined
2022-09-05 15:36:34,918 INFO: Microblog startup [in /src/app/__init__.py:59
2022-09-05 15:36:50,430 INFO: Microblog startup [in /src/app/__init__.py:59
2022-09-05 15:36:55,062 INFO: Microblog startup [in /src/app/__init__.py:59
2022-09-05 15:37:01,808 INFO: Microblog startup [in /src/app/__init__.py:59
2022-09-05 15:37:08,033 ERROR: Exception on /translate [POST] [in /usr/lib/python3.10/site-packages/flask/app.py:1455
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/src/app/routes.py", line 203, in translate_text
    return jsonify({'text': translate(request.form['text'],
NameError: name 'translate' is not defined
2022-09-05 15:37:36,285 INFO: Microblog startup [in /src/app/__init__.py:59
